### ISSUE TITLE
大佬，有个错误我想问一下，好像是ld那里的错误

### ISSUE THREAD

**Issue by crossbow256** [ghosind/HariboteOS#2]
推进到第三天的时候，我试着用您的文件make了一下，但是出现了一些问题，是ld非32位的问题吗，我有点懵，能不能告诉我，多谢了，系统环境是64位的ubuntu20.04
![Screenshot from 2022-04-05 04-51-34](https://user-images.githubusercontent.com/95999166/161630559-5eb4817d-9b25-4b6e-baaf-9a2b16c235a7.png)

**Comment by ghosind** [comment]
Hi
因为我是在MacOS下使用`x86_64-elf-gcc`这套工具链编译的，我刚才在Ubuntu下验证了一下，同样无法编译成功，应该是二者默认的编译参数不同导致的。
对于这个编译时的问题，我在WSL中验证后可以添加`-fno-pie`参数解决，所以您可以尝试在Makefile中的`CFLAGS`里面加上`-fno-pie`选项，我稍后也会重新提交一个commit显式加入这个选项，谢谢对于这个问题的反馈:D

**Comment by crossbow256** [comment]
thank you,大佬
