### ISSUE TITLE
a.c:(.text+0x16): undefined reference to `_GLOBAL_OFFSET_TABLE_'

### ISSUE THREAD

**Issue by mingzhanliao** [ghosind/HariboteOS#5]
推进到21天时，有这个错误
gcc 版本 gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 

gcc -Wall -Wno-format -Wno-unused -std=gnu99 -static -m32 -I ./include -I ../libc/include -ffunction-sections -nostdlib -nostdinc -fno-builtin -ffreestanding -fno-pie -c fs.c -o fs.bin
gcc -Wall -Wno-format -Wno-unused -std=gnu99 -static -m32 -I ./include -I ../libc/include -ffunction-sections -nostdlib -nostdinc -fno-builtin -ffreestanding -fno-pie -c command.c -o command.bin
gcc -Wall -Wno-format -Wno-unused -std=gnu99 -static -m32 -I ./include -I ../libc/include -ffunction-sections -nostdlib -nostdinc -fno-builtin -ffreestanding -fno-pie -c api.c -o api.bin
nasm -f elf api_asm.asm -o api_asm.bin -l api_asm.lst
nasm -f elf app.asm -o app.bin -l app.lst
nasm -f bin app/hello.asm -o app/hello.hrb  -l app/hello.lst
nasm -f bin app/hello2.asm -o app/hello2.hrb  -l app/hello2.lst
nasm -f elf app/a_asm.asm -o app/a_asm.o
gcc -Wall -Wno-format -Wno-unused -std=gnu99 -m32 -c app/a.c -o app/a.o
ld -m elf_i386 --oformat binary -e main app/a.o app/a_asm.o -o app/a.hrb
ld: app/a.o: in function `main':
a.c:(.text+0x16): undefined reference to `_GLOBAL_OFFSET_TABLE_'
make: *** [Makefile:63: app/a.hrb] Error 1

**Comment by ghosind** [comment]
Hi，可以参考[https://stackoverflow.com/a/45422495](https://stackoverflow.com/a/45422495)这个回答，应当是Ubuntu下GCC默认参数开启了PIE，需要在编译时增加`fno-pie`参数。稍晚些时候我会修改一下Makefile文件增加该参数。

**Comment by mingzhanliao** [comment]
实际上已经增加了这个参数,还是有这个错误

**Comment by ghosind** [comment]
不好意思，我在Ubuntu 22.04下也无法在最新的代码下重现该错误，麻烦确认一下是否已经拉取了最新的代码。如果还是有错误的话，是否方便通过`gcc -v`提供一下完整的GCC信息？

**Comment by mingzhanliao** [comment]
拉了最新代码，问题已解决，谢谢
